### ISSUE TITLE
IntelliJ wrongly detects module errors in test sources

### ISSUE THREAD

**Issue by carltonwhitehead** [ilya-g/kotlin-jlink-examples#3]
In the Maven project, in `Test.kt`, IntelliJ displays a lint error on references to junit:

```no-highlight
Symbol is declared in module 'kotlin.test' which current module does not depend on
```

This doesn't affect builds, just developer experience in IntelliJ. I suspect it might even be a local configuration issue or an IntelliJ bug, but I wanted to raise this here first to see if anyone else is seeing this and/or knows how to resolve it before investigating further.

**Comment by ilya-g** [comment]
Thanks for noticing this. 
It looks like a problem in Kotlin plugin, I've reported it as https://youtrack.jetbrains.com/issue/KT-41317
